cron1:
  cpu: 256
  memory: 512
  enabled: true
  schedule: "cron(0 15 ? * WED *)"
  timezone: "Asia/Kolkata"

cron2:
  cpu: 256
  memory: 512
  enabled: true
  schedule: "cron(30 15 ? * WED *)"
  timezone: "Asia/Kolkata"

cron3:
  cpu: 256
  memory: 512
  enabled: true
  schedule: "cron(0 16 ? * WED *)"
  timezone: "Asia/Kolkata"

cron4:
  cpu: 256
  memory: 512
  enabled: true
  schedule: "cron(30 16 ? * WED *)"
  timezone: "Asia/Kolkata"

cron5:
  cpu: 256
  memory: 512
  enabled: true
  schedule: "cron(0 17 ? * WED *)"
  timezone: "Asia/Kolkata"
