name: Build Changed Cron

on:
  push:
    branches:
      - main
    paths:
      - "tasks/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "229531317968"

jobs:
  detect-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed cron folders
        id: detect
        shell: bash
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          CRONS=$(echo "$CHANGED_FILES" \
            | grep '^tasks/' \
            | cut -d/ -f2 \
            | sort -u)

          echo "Changed cron jobs:"
          echo "$CRONS"

          echo "crons=$CRONS" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::229531317968:role/github-central-cron-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push changed cron images
        shell: bash
        run: |
          for CRON in ${{ steps.detect.outputs.crons }}; do

            echo "Building $CRON"

            ECR_REPO="229531317968.dkr.ecr.us-east-1.amazonaws.com/central-cron/$CRON"

            docker build \
              -t "$ECR_REPO:${GITHUB_SHA}" \
              -t "$ECR_REPO:latest" \
              "tasks/$CRON"

            docker push "$ECR_REPO:${GITHUB_SHA}"
            docker push "$ECR_REPO:latest"

            echo "Successfully pushed $CRON"
          done
